const stores={
 food:{name:"RAPIDO'S FOODLAND",sign:'FRESH • FAST • FUN',shelves:['PANTRY','FRESH PICKS'],items:[['Golden Apples',4.5,'🍎','#ed6554',31,58],['Mega Cereal',7.25,'🌟','#6e87d5',42,46],['Fresh Milk',5,'🥛','#e8f4f5',56,65],['Snack Stack',3.8,'🥨','#ee914c',68,45],['Power Juice',8.9,'🍊','#f2a23e',78,61],['Super Bites',6.6,'🍪','#c96f50',16,55],['Bread Loaf',3.25,'🍞','#d49a55',25,37],['Berry Box',6.45,'🫐','#5d6ec2',37,33],['Cheese Wheel',7.9,'🧀','#f7c34f',51,36],['Pasta Pack',4.2,'🍝','#e7b84b',63,33],['Iced Tea',3.6,'🧃','#f09349',73,39],['Cake Slice',9.5,'🍰','#f2819a',85,45]]},
 tech:{name:'TECHNO EXPRESS',sign:'POWER • PLAY • CONNECT',shelves:['GADGETS','GAMING'],items:[['Smart Watch',149,'⌚','#59b5e6',31,58],['Gaming Pad',65,'🎮','#9b69d3',42,46],['Headphones',89,'🎧','#ef674e',56,65],['Phone Pro',399,'📱','#4d789d',68,45],['Camera',249,'📷','#e2a543',78,61],['Laptop Air',599,'💻','#82bc9f',16,55],['VR Headset',319,'🥽','#4d5f79',25,37],['Smart Speaker',99,'🔊','#6c8dd2',37,33],['Keyboard',119,'⌨️','#7d7d90',51,36],['Drone Mini',179,'🚁','#e8a54c',63,33],['Power Bank',49,'🔋','#62ae7a',73,39],['Game Console',449,'🕹️','#e06c93',85,45]]}
};
// Extra stock opens up deeper store aisles as the player moves through the space.
stores.food.items.push(
 ['Spring Water',2.25,'💧','#54b8dd',12,66],['Sparkling Water',3.1,'🫧','#7fcde1',23,70],
 ['Iced Tea',3.6,'🧋','#c77c3d',35,69],['Empanadas',8.5,'🥟','#db9c49',47,70],
 ['Family Pizza',14.9,'🍕','#db7040',59,70],['Tomato Pasta',6.75,'🍝','#dca84e',71,70],
 ['Orange Soda',2.9,'🥤','#ee813c',84,68],['Salad Bowl',7.2,'🥗','#70ae68',11,44],
 ['Yogurt Pack',5.5,'🍦','#a06ab8',84,34],['Coffee Beans',11.4,'☕','#915b3e',48,29]
);
stores.tech.items.push(
 ['Ultra TV',899,'📺','#53627c',12,66],['Soundbar Pro',179,'🔊','#44505d',23,70],
 ['Smart Fridge',1099,'🧊','#a9bfcc',35,69],['Air Fryer',129,'🍳','#394653',47,70],
 ['Robot Vacuum',279,'🤖','#71849a',59,70],['Blender Max',99,'🥤','#e0604b',71,70],
 ['Coffee Machine',189,'☕','#44515e',84,68],['Microwave',159,'📦','#74838f',11,44],
 ['Washing Machine',649,'🧺','#607b95',84,34],['Projector',329,'📽️','#d0b253',48,29]
);
const currencyInfo={usd:{symbol:'$',name:'DOLLARS',code:'USD',rate:1},eur:{symbol:'€',name:'EUROS',code:'EUR',rate:.92},jpy:{symbol:'¥',name:'YENS',code:'JPY',rate:148}};
let settings={store:'food',avatar:'orange',sex:'female',currency:'usd',name:'YOU'},groceries=[],cart=[],teamBasket=[],playerX=48,playerY=73,playerBudget=999,active=false,paused=false,tutorialActive=false,tutorialStep=0,step=0,timerId=null,botTimer=null,waitTimer=null,seconds=300,playMode='solo',battleMode='ffa',comPlayers=[],finalStandings=[],roundResults=null;
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="multiplayer.css" />');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="pause.css" /><link rel="stylesheet" href="waiting.css" /><link rel="stylesheet" href="teamhud.css" /><link rel="stylesheet" href="inventory.css" /><link rel="stylesheet" href="teamresults.css" /><link rel="stylesheet" href="tutorial.css" />');
document.head.insertAdjacentHTML('beforeend','<style>.shopper3d.outfit-orange{--ol:#ff9a55;--od:#dd4d37;--os:#ae3d35}.shopper3d.outfit-blue{--ol:#75c8fb;--od:#3976bf;--os:#28598f}.shopper3d.outfit-green{--ol:#77d9ae;--od:#238d68;--os:#17664c}.shopper3d.outfit-yellow{--ol:#f5d45b;--od:#cd902a;--os:#9a671c}.shopper3d.outfit-pink{--ol:#f59bc1;--od:#bf477c;--os:#8e315b}.shopper3d.outfit-black{--ol:#586174;--od:#222b3c;--os:#131a27}.shopper3d[class*="outfit-"] .torso3d{background:linear-gradient(110deg,var(--ol) 0 50%,var(--od) 51%);box-shadow:inset 5px 2px #ffffff66,5px 6px var(--os)}.shopper3d[class*="outfit-"] .arm3d{background:linear-gradient(90deg,var(--ol),var(--od));box-shadow:2px 2px var(--os)}</style>');
document.head.insertAdjacentHTML('beforeend','<style>.name-team-icon{display:block;font-style:normal;font-size:15px;line-height:12px}.com-name .name-team-icon{margin-bottom:1px}</style>');
const titleActions=document.createElement('div');titleActions.className='title-actions';
const soloButton=$('#start');soloButton.textContent='TUTORIAL';soloButton.innerHTML='TUTORIAL <strong>SPACE</strong>';
const comButton=document.createElement('button');comButton.className='com-button';comButton.textContent='PLAY WITH COM';
const multiButton=document.createElement('button');multiButton.className='multi-button';multiButton.textContent='MULTIPLAYER';
const budgetCard=document.createElement('div');budgetCard.className='budget-card';budgetCard.innerHTML='<span>YOUR BUDGET</span><b id="budget">$999.00</b>';$('#game header').append(budgetCard);
soloButton.replaceWith(titleActions);titleActions.append(soloButton,comButton,multiButton);
const modeScreen=document.createElement('section');modeScreen.id='mode-select';modeScreen.className='screen setup-screen';modeScreen.innerHTML='<div class="setup-head"><img class="brand-logo header-logo" src="supermarket-rapido-logo.png" alt="Supermarket Rapido"><span>COM MATCH</span></div><div class="setup-panel active mode-panel"><p class="kicker">PLAY WITH COM</p><h1>SELECT MODE</h1><div class="mode-grid"><button class="mode-choice selected" data-battle="ffa"><span>⚔️</span><strong>FREE-FOR-ALL</strong><small>Every shopper for themselves.</small></button><button class="mode-choice" data-battle="team"><span>🤝</span><strong>TEAM</strong><small>Work with a COM teammate.</small></button></div><button id="mode-next" class="next">NEXT →</button></div><div class="key-help"><kbd>ESC</kbd> BACK <span><kbd>SPACE</kbd> SELECT</span></div></section>';
document.querySelector('main').append(modeScreen);
const multiModal=document.createElement('div');multiModal.className='modal-shade';multiModal.hidden=true;multiModal.innerHTML='<div class="soon-card"><span class="big-icon">🌐</span><h2>MULTIPLAYER<br>COMING SOON!</h2><p>We\'re working in!<br>Come back later!</p><button>GOT IT</button></div>';document.querySelector('main').append(multiModal);
const roster=document.createElement('div');roster.id='com-roster';roster.className='com-roster';$('.character-select').after(roster);
const creator=$('.character-select');creator.className='character-select live-preview';creator.innerHTML='<div class="preview-frame"><div id="creator-preview" class="character3d shopper3d"><div class="hair3d"></div><div class="head3d"><i></i><i></i><b></b></div><div class="torso3d"></div><div class="arm3d left-arm"></div><div class="arm3d right-arm"></div><div class="leg3d left-leg"></div><div class="leg3d right-leg"></div></div></div>';
const customizer=$('.customize');customizer.innerHTML='<label>PLAYER NAME <input id="player-name" maxlength="10" autocomplete="nickname" /></label><div class="sex-choice"><span>SEX</span><button data-sex="female" class="selected">FEMALE</button><button data-sex="male">MALE</button></div><div><span>OUTFIT</span><button class="swatch orange selected" data-color="orange"></button><button class="swatch blue" data-color="blue"></button><button class="swatch green" data-color="green"></button><button class="swatch yellow" data-color="yellow"></button><button class="swatch pink" data-color="pink"></button><button class="swatch black" data-color="black"></button></div>';
const comArea=document.createElement('div');comArea.id='com-players';$('#items').after(comArea);
const teamHud=document.createElement('div');teamHud.id='team-hud';$('#game .store').append(teamHud);
const pauseMenu=document.createElement('div');pauseMenu.id='pause-menu';pauseMenu.hidden=true;pauseMenu.innerHTML='<div class="pause-card"><img class="pause-logo" src="supermarket-rapido-logo.png" alt="Supermarket Rapido"><h2>PAUSED</h2><p class="pause-cart">YOUR CART <b id="pause-total">$0.00</b></p><button id="resume-game">RESUME</button><button id="quit-game" class="quit">QUIT</button><div id="quit-confirm" class="quit-confirm" hidden><p>Are you sure you want to quit?</p><button id="quit-yes" class="quit">YES</button><button id="quit-no" class="no">NO</button></div></div>';$('#game').append(pauseMenu);
const tutorialPanel=document.createElement('div');tutorialPanel.id='tutorial-panel';tutorialPanel.hidden=true;$('#game .store').append(tutorialPanel);
const tutorialComplete=document.createElement('section');tutorialComplete.id='tutorial-complete';tutorialComplete.className='screen';tutorialComplete.innerHTML='<div class="tutorial-complete-card"><div class="complete-icon">🏆</div><h1>TUTORIAL COMPLETED!</h1><p>You mastered movement, shopping, and checkout.</p><button id="retry-tutorial">RETRY TUTORIAL</button><button id="tutorial-title" class="return-title">RETURN TO TITLE SCREEN</button></div>';document.querySelector('main').append(tutorialComplete);
const waitingScreen=document.createElement('section');waitingScreen.id='waiting';waitingScreen.className='screen';waitingScreen.innerHTML='<img class="waiting-logo" src="supermarket-rapido-logo.png" alt="Supermarket Rapido"><div class="waiting-card"><p>CHECKOUT COMPLETE</p><h1>WAITING FOR PLAYERS</h1><p>Other shoppers are finishing their orders.</p><div id="waiting-players"></div><div class="wait-dots">•••</div></div>';document.querySelector('main').append(waitingScreen);
function teamNames(){return settings.store==='food'?['TEAM APPLE','TEAM ICE TEA']:['TEAM TV','TEAM MICROWAVE']}
function teamIconFor(team){if(battleMode!=='team')return '';const [first,second]=teamNames();if(settings.store==='food')return team===first?'🍎':'🧊';return team===first?'📺':'🍽️'}
function assignTeams(){if(battleMode!=='team')return;const [first,second]=teamNames(),palette=['orange','blue','green','yellow','pink','black'];if(!settings.opponentOutfit||settings.opponentOutfit===settings.avatar)settings.opponentOutfit=palette.find(color=>color!==settings.avatar&&color!==settings.opponentOutfit)||'blue';comPlayers.forEach((bot,index)=>{bot.team=index<2?first:second;bot.outfit=index<2?settings.avatar:settings.opponentOutfit});settings.team=first}
function isTeamMatch(){return playMode==='com'&&battleMode==='team'}
function activeBasket(){return isTeamMatch()?teamBasket:cart}
function randomizeComPlayers(){const names=['BYTE BOT','NOVA COM','PIXEL AI','GEAR UNIT','ORBIT BOT'];const outfits=['orange','blue','green','yellow','pink'];const spots=[[18,62],[33,48],[50,57],[68,43],[83,60]];comPlayers=names.map((name,i)=>({name,outfit:outfits[(i+Math.floor(Math.random()*outfits.length))%outfits.length],score:0,budget:999,x:spots[i][0],y:spots[i][1],target:null,taken:0,team:null}));assignTeams();renderRoster()}
function renderRoster(){if(playMode!=='com'){roster.hidden=true;return}assignTeams();roster.hidden=false;const human=settings.name||'YOU';if(battleMode==='team'){const [first,second]=teamNames();const icon=settings.store==='food'?['🍎','🧊']:['📺','🍽️'];const card=(name,color,isHuman=false)=>`<div class="team-card ${isHuman?'human':''}">${isHuman?'':`<i class="robot">🤖</i>`}<i class="player-circle" style="--member-color:${color}"></i>${name}</div>`;roster.className='setup-team-strip';roster.innerHTML=`<aside class="team-edge apple"><div><span class="team-icon">${icon[0]}</span>${first}</div></aside><div class="team-roster">${card(human,outfitColor(settings.avatar),true)}${comPlayers.map(p=>card(p.name,outfitColor(p.outfit))).join('')}</div><aside class="team-edge ice"><div><span class="team-icon">${icon[1]}</span>${second}</div></aside>`;return}roster.className='com-roster';roster.innerHTML=`<span class="roster-player human"><i class="dot" style="--outfit:${outfitColor(settings.avatar)}"></i>${human}</span>`+comPlayers.map(p=>`<span class="roster-player"><i class="bot">🤖</i><i class="dot" style="--outfit:${outfitColor(p.outfit)}"></i>${p.name}</span>`).join('')}
function outfitColor(outfit){return({orange:'#ff7c57',blue:'#559de4',green:'#52bb82',yellow:'#e6bd3f',pink:'#e46fa7',black:'#536074'})[outfit]||'#ff7c57'}
function renderTeamHud(){teamHud.innerHTML=''}
function renderComPlayers(){if(playMode!=='com'){comArea.innerHTML='';return}comArea.innerHTML=comPlayers.map(p=>`<div class="com-shopper ${p.outfit} ${p.team===settings.team?'ally':'rival'}" style="left:${p.x}%;top:${p.y}%"><div class="character3d shopper3d outfit-${p.outfit}"><div class="hair3d"></div><div class="head3d"><i></i><i></i><b></b></div><div class="torso3d"></div><div class="arm3d left-arm"></div><div class="arm3d right-arm"></div><div class="leg3d left-leg"></div><div class="leg3d right-leg"></div><em>🛒${p.taken||''}</em></div><span class="com-name">${teamIconFor(p.team)?`<i class="name-team-icon">${teamIconFor(p.team)}</i>`:''}🤖 ${p.name}</span></div>`).join('')}
function startBots(){clearInterval(botTimer);if(playMode!=='com')return;botTimer=setInterval(()=>{if(!active||paused)return;comPlayers.forEach((bot,index)=>{let target=groceries[bot.target];if(!target||target.stock<=0){const available=groceries.map((g,i)=>({g,i})).filter(x=>x.g.stock>0&&bot.budget>=currencyAmount(x.g.price));if(!available.length)return;const choice=available[Math.floor(Math.random()*available.length)];bot.target=choice.i;target=choice.g}bot.x+=Math.sign(target.x-bot.x)*Math.min(4,Math.abs(target.x-bot.x));bot.y+=Math.sign(target.y-bot.y)*Math.min(3,Math.abs(target.y-bot.y));if(Math.hypot(target.x-bot.x,target.y-bot.y)<6){const cost=currencyAmount(target.price);if(target.stock>0&&bot.budget>=cost){target.stock--;bot.budget-=cost;bot.score+=target.price;bot.taken++;if(isTeamMatch()&&bot.team===settings.team)teamBasket.push({...target,owner:bot.name});update();draw()}bot.target=null}const botNode=comArea.children[index];if(botNode){botNode.style.left=bot.x+'%';botNode.style.top=bot.y+'%';botNode.querySelector('em').textContent='🛒'+(bot.taken||'')}})},850)}
const nameError=document.createElement('small');
nameError.id='name-error';nameError.className='name-error';nameError.textContent='Player Name is required.';nameError.hidden=true;nameError.style.cssText='color:#ffe371;font-size:11px;font-weight:900;margin-top:2px';
$('#player-name').after(nameError);
$('#player-name').value='';
function validateName(){const value=$('#player-name').value.trim(),input=$('#player-name'),invalid=!value;nameError.hidden=!invalid;input.style.borderColor=invalid?'#ff7659':'#a8e3bc';input.style.boxShadow=invalid?'0 0 0 3px #fb614244':'none';if(!invalid){settings.name=value.toUpperCase();renderRoster()}return !invalid}
function currencyAmount(n){const c=currencyInfo[settings.currency],amount=n*c.rate;return settings.currency==='jpy'?Math.round(amount):Number(amount.toFixed(2))}
function format(n){const c=currencyInfo[settings.currency],amount=currencyAmount(n);return c.symbol+(settings.currency==='jpy'?amount:amount.toFixed(2))}
function formatBudget(amount){const c=currencyInfo[settings.currency];return c.symbol+(settings.currency==='jpy'?Math.round(amount):amount.toFixed(2))}
function changeScreen(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function selectOne(selector,current){$$(selector).forEach(b=>b.classList.toggle('selected',b===current))}
function showStep(n){step=Math.max(0,Math.min(2,n));$$('#setup .setup-panel').forEach((p,i)=>p.classList.toggle('active',i===step));$('#step-count').textContent=`${step+1} / 3`}
function applyAvatar(node){node.classList.remove('blue','violet','coral','outfit-orange','outfit-blue','outfit-green','outfit-yellow','outfit-pink','outfit-black','sex-female','sex-male');node.classList.add('outfit-'+settings.avatar,'sex-'+settings.sex)}
applyAvatar($('#creator-preview'));
function updateReady(){const c=currencyInfo[settings.currency];$('#ready-name').textContent=settings.name||'YOU';$('#ready-location').textContent=stores[settings.store].name;$('#ready-currency').textContent=`${c.name} (${c.code})`;applyAvatar($('#ready-avatar'))}
function openSetup(mode='solo'){tutorialActive=false;playMode=mode;changeScreen('setup');showStep(0);renderRoster()}
const tutorialTasks=[['MOVE FORWARD','Press <kbd>W</kbd> to walk toward the back of the store.'],['MOVE BACK','Great! Now press <kbd>S</kbd> to return.'],['STRAFE LEFT','Try moving sideways with <kbd>A</kbd>.'],['STRAFE RIGHT','Now move right with <kbd>D</kbd>.'],['SHOPPING TIME','Walk close to any product and press <kbd>T</kbd> to add it to your basket.'],['CHECKOUT CHALLENGE','Take your basket close to either cashier or register and press <kbd>E</kbd>.']];
function renderTutorial(){if(!tutorialActive){tutorialPanel.hidden=true;return}const task=tutorialTasks[tutorialStep]||tutorialTasks[tutorialTasks.length-1];tutorialPanel.hidden=false;tutorialPanel.innerHTML=`<div class="tutorial-step">EXERCISE ${Math.min(tutorialStep+1,tutorialTasks.length)} / ${tutorialTasks.length}</div><div class="tutorial-task"><b>${task[0]}:</b> ${task[1]}</div><div class="tutorial-progress"><i style="width:${(tutorialStep/tutorialTasks.length)*100}%"></i></div>`}
function advanceTutorial(){if(!tutorialActive)return;tutorialStep++;if(tutorialStep>=tutorialTasks.length){tutorialStep=tutorialTasks.length-1;return}renderTutorial()}
function startTutorial(){playMode='solo';battleMode='ffa';tutorialActive=true;tutorialStep=0;settings.store='food';settings.currency='usd';settings.name=settings.name||'ROOKIE';launch()}
function showTutorialComplete(){changeScreen('tutorial-complete')}
function openModeSelect(){playMode='com';changeScreen('mode-select');modeScreen.classList.add('active')}
function toReady(){updateReady();renderRoster();changeScreen('ready')}
function makeItems(){groceries=stores[settings.store].items.map(([name,price,icon,color,x,y,stock=3],index)=>({id:`${settings.store}-${index}`,name,price,icon,color,x,y,stock,maxStock:stock}))}
function draw(){const area=$('#items');area.innerHTML='';groceries.forEach((g,i)=>{const soldOut=g.stock<=0,e=document.createElement('button');e.className=`item ${soldOut?'sold-out':''}`;e.disabled=soldOut;e.dataset.index=i;const scale=.64+g.y/130;e.style.cssText=`left:${g.x}%;top:${g.y}%;--color:${g.color};--item-scale:${scale};z-index:${Math.round(g.y*10)}`;e.innerHTML=`<b class="stock-count">${soldOut?'0 LEFT':g.stock+' LEFT'}</b><b class="price">${soldOut?'SOLD OUT':format(g.price)}</b><span class="box" data-icon="${g.icon}"></span><small>${g.name}</small>`;e.onclick=()=>tryTake(i);area.append(e)});updateTakePrompt()}
function update(){const basket=activeBasket(),sum=basket.reduce((a,g)=>a+g.price,0);$('#total').textContent=format(sum);$('#regtotal').textContent=format(sum);$('#pause-total').textContent=format(sum);$('#budget').textContent=formatBudget(playerBudget);$('#cart').innerHTML=basket.length?basket.map(g=>`<span class="chip">${g.icon} ${g.name}</span>`).join(''):'Your basket is empty!';$('#player em').textContent=basket.length?`🛒${basket.length}`:'🛒'}
function nearestItem(){let match=null,best=Infinity;groceries.forEach((g,i)=>{if(g.stock<=0)return;const d=Math.hypot((g.x-playerX)*.78,(g.y-playerY));if(d<best){best=d;match={g,i,d}}});return match}
function nearCheckout(){const player=$('#player').getBoundingClientRect(),checkoutZone=$('#checkout').getBoundingClientRect(),playerCenter={x:player.left+player.width/2,y:player.top+player.height/2},checkoutCenter={x:checkoutZone.left+checkoutZone.width/2,y:checkoutZone.top+checkoutZone.height/2};return Math.hypot(playerCenter.x-checkoutCenter.x,playerCenter.y-checkoutCenter.y)<150}
function updateTakePrompt(){const near=nearestItem(),hint=$('.instructions');$$('.item').forEach(e=>e.classList.remove('near'));if(nearCheckout()){hint.textContent='PRESS E TO CHECK OUT AT THE REGISTER';return}if(near&&near.d<8){const el=$(`.item[data-index="${near.i}"]`);if(el)el.classList.add('near');hint.textContent=`PRESS T TO TAKE ${near.g.name.toUpperCase()}`}else hint.textContent='W/S: forward & back • A/D: move sideways • T: take item'}
function tryTake(index){const near=nearestItem();if(index!==undefined&&(!near||near.i!==index))return;if(!near||near.d>=8||!active||paused)return;const g=near.g,cost=currencyAmount(g.price);if(playerBudget<cost){$('.instructions').textContent='NOT ENOUGH BUDGET FOR THIS ITEM';return}playerBudget-=cost;g.stock--;const item={...g,owner:settings.name};cart.push(item);if(isTeamMatch())teamBasket.push(item);if(tutorialActive&&tutorialStep===4)advanceTutorial();update();draw()}
function updatePlayer(walking=false){const player=$('#player'),scale=.58+playerY/110;player.style.left=playerX+'%';player.style.top=playerY+'%';player.style.bottom='auto';player.style.zIndex=Math.round(playerY*10);player.style.transform=`scale(${scale})`;player.classList.toggle('walking',walking);updateTakePrompt()}
function refreshLeaderboard(){const board=$('.board'),name=settings.name||'YOU',playerScore=cart.reduce((total,item)=>total+item.price,0);if(playMode==='com'){const rows=[{name,score:playerScore,human:true},...comPlayers].sort((a,b)=>b.score-a.score);board.innerHTML=rows.map(p=>`${p.human?'':'<span class="bot">🤖</span>'}${p.name} <b>${format(p.score)}</b>`).join('<br>')}else board.innerHTML=`${name} <b>${format(playerScore)}</b><br>CASA CART <b>${format(18.75)}</b><br>QUICK MARTY <b>${format(13.2)}</b>`}
function buildFinalStandings(finalScore){const human={name:settings.name||'YOU',score:Number(finalScore),human:true};if(playMode==='com'){comPlayers.forEach(bot=>{if(!Number.isFinite(bot.score)||bot.score<=0)bot.score=finalScore*(.25+Math.random()*.65)});if(isTeamMatch()){const [first,second]=teamNames();finalStandings=[{name:first,score:finalScore+comPlayers.filter(bot=>bot.team===first).reduce((sum,bot)=>sum+bot.score,0),human:true,team:'apple',icon:teamIconFor(first)},{name:second,score:comPlayers.filter(bot=>bot.team===second).reduce((sum,bot)=>sum+bot.score,0),human:false,team:'ice',icon:teamIconFor(second)}]}else finalStandings=[human,...comPlayers.map(bot=>({name:bot.name,score:Number(bot.score),human:false}))]}else finalStandings=[human,{name:'CASA CART',score:18.75,human:false},{name:'QUICK MARTY',score:13.2,human:false}];finalStandings.sort((a,b)=>b.score-a.score);return finalStandings}
function renderFinalLeaderboard(finalScore){const rows=isTeamMatch()?buildFinalStandings(finalScore):(roundResults||buildFinalStandings(finalScore)),board=$('.board');if(isTeamMatch()){board.className='board team-result-table';board.innerHTML='<div class="team-result-row header"><span>Rank</span><span>Team Name</span><b>Amount</b></div>'+rows.map((team,index)=>`<div class="team-result-row ${team.team}"><span>#${index+1}</span><span><i class="team-result-icon">${team.icon}</i>${team.name}</span><b>${format(team.score)}</b></div>`).join('')}else{board.className='board';board.innerHTML=rows.map((p,index)=>`#${index+1} ${p.human?'':'<span class="bot">🤖</span>'}${p.name} <b>${format(p.score)}</b>`).join('<br>')}return rows[0]}
function reset(){roundResults=null;cart=[];teamBasket=[];playerBudget=999;playerX=48;playerY=73;if(playMode==='com'){const spots=[[18,62],[33,48],[50,57],[68,43],[83,60]];assignTeams();comPlayers.forEach((bot,i)=>Object.assign(bot,{score:0,budget:999,taken:0,target:null,x:spots[i][0],y:spots[i][1]}))}makeItems();const playerTeamIcon=teamIconFor(settings.team);$('#player label').innerHTML=`${playerTeamIcon?`<i class="name-team-icon">${playerTeamIcon}</i>`:''}${settings.name||'YOU'}`;applyAvatar($('#player'));update();draw();updatePlayer();refreshLeaderboard()}
function setTimer(){const m=Math.floor(seconds/60),s=seconds%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('warning',seconds<=60)}
function runTimer(){clearInterval(timerId);timerId=setInterval(()=>{seconds--;setTimer();if(seconds<=0){clearInterval(timerId);checkout(true)}},1000)}
function startTimer(){seconds=300;setTimer();runTimer()}
function pauseGame(){if(!active||paused)return;paused=true;clearInterval(timerId);clearInterval(botTimer);$('#game').classList.add('paused');pauseMenu.hidden=false;$('#quit-confirm').hidden=true}
function resumeGame(){if(!paused)return;paused=false;$('#game').classList.remove('paused');pauseMenu.hidden=true;runTimer();startBots()}
function quitToTitle(){clearInterval(timerId);clearInterval(botTimer);clearInterval(waitTimer);active=false;paused=false;tutorialActive=false;tutorialPanel.hidden=true;pauseMenu.hidden=true;$('#game').classList.remove('paused','tutorial');changeScreen('title')}
function launch(){changeScreen('game');active=true;$('#game').classList.toggle('tutorial',tutorialActive);$('#game').classList.toggle('com-match',playMode==='com');$('#game-location').textContent=stores[settings.store].name;$('#back-sign').textContent=stores[settings.store].sign;$('#shelf-left').textContent=stores[settings.store].shelves[0];$('#shelf-right').textContent=stores[settings.store].shelves[1];reset();renderComPlayers();renderTeamHud();renderTutorial();startBots();startTimer()}
function move(dx,dy){if(!active||paused)return;playerX=Math.max(7,Math.min(88,playerX+dx));playerY=Math.max(28,Math.min(76,playerY+dy));if(tutorialActive&&((tutorialStep===0&&dy<0)||(tutorialStep===1&&dy>0)||(tutorialStep===2&&dx<0)||(tutorialStep===3&&dx>0)))advanceTutorial();updatePlayer(true);clearTimeout(move.stop);move.stop=setTimeout(()=>$('#player').classList.remove('walking'),125)}
function paintFinalBoard(rows){if(isTeamMatch()){renderFinalLeaderboard(cart.reduce((sum,item)=>sum+item.price,0));return}const board=$('.board');board.className='board';board.innerHTML=rows.map((player,index)=>`#${index+1} ${player.human?'':'<span class="bot">🤖</span>'}${player.name} <b>${format(player.score)}</b>`).join('<br>')}
function enforceFinalBoard(){if(!$('#results').classList.contains('active')||!cart.length)return;const rows=roundResults||buildFinalStandings(cart.reduce((sum,item)=>sum+item.price,0));const signature=rows.map(player=>`${player.name}:${player.score}`).join('|');if($('.board').dataset.roundSignature!==signature){paintFinalBoard(rows);$('.board').dataset.roundSignature=signature}}
new MutationObserver(enforceFinalBoard).observe($('#results'),{attributes:true,attributeFilter:['class']});
function showResults(sum,outOfTime=false){changeScreen('results');const winner=renderFinalLeaderboard(sum),teamScore=isTeamMatch()?finalStandings.find(team=>team.human).score:sum;$('#results .card > span').textContent=isTeamMatch()?'Your Team checked out with':'You checked out with';$('#final').textContent=format(teamScore);$('#your-score').textContent=format(teamScore);$('#winner').textContent=outOfTime?'TIME UP!':winner.human?'SUPER SHOPPER!':winner.name+' WINS!';$('#results-kicker').textContent=outOfTime?'THE CLOCK RAN OUT':winner.human?stores[settings.store].name+' WINNER':'TOP SHOPPER';setTimeout(()=>paintFinalBoard(roundResults||buildFinalStandings(sum)),50)}
function renderWaiting(){const list=$('#waiting-players');list.innerHTML=comPlayers.map(bot=>`<div class="wait-row ${bot.finished?'done':''}"><span><i class="robot">🤖</i>${bot.name}${battleMode==='team'?` · ${bot.team}`:''}</span><span class="status">${bot.finished?'ORDER FINISHED ✓':'CHECKING OUT...'}</span></div>`).join('')}
function waitForPlayers(sum,outOfTime){comPlayers.forEach(bot=>bot.finished=false);changeScreen('waiting');renderWaiting();let next=0;clearInterval(waitTimer);waitTimer=setInterval(()=>{const bot=comPlayers[next++];if(bot){bot.score=Math.max(bot.score,sum*(.25+Math.random()*.65));bot.finished=true;renderWaiting()}if(next>=comPlayers.length){clearInterval(waitTimer);roundResults=[{name:settings.name||'YOU',score:Number(sum),human:true},...comPlayers.map(bot=>({name:bot.name,score:Number(bot.score),human:false}))].sort((a,b)=>b.score-a.score);setTimeout(()=>showResults(sum,outOfTime),650)}},900)}
function checkout(outOfTime=false){if(!active||paused)return;if(!outOfTime&&!nearCheckout())return;if(tutorialActive&&!outOfTime&&tutorialStep<5){renderTutorial();return}if(!cart.length&&!outOfTime)return;const completedTutorial=tutorialActive;active=false;tutorialActive=false;tutorialPanel.hidden=true;$('#game').classList.remove('tutorial');clearInterval(timerId);clearInterval(botTimer);if(completedTutorial){showTutorialComplete();return}const sum=cart.reduce((a,g)=>a+g.price,0);if(playMode==='com')waitForPlayers(sum,outOfTime);else showResults(sum,outOfTime)}
$('#start').onclick=startTutorial;comButton.onclick=()=>openModeSelect();comButton.addEventListener('pointerup',event=>{event.preventDefault();openModeSelect()});multiButton.onclick=()=>multiModal.hidden=false;multiModal.querySelector('button').onclick=()=>multiModal.hidden=true;$('#launch').onclick=launch;$('#again').onclick=()=>openSetup(playMode);$('#resume-game').onclick=resumeGame;$('#quit-game').onclick=()=>$('#quit-confirm').hidden=false;$('#quit-no').onclick=()=>$('#quit-confirm').hidden=true;$('#quit-yes').onclick=quitToTitle;$('#retry-tutorial').onclick=startTutorial;$('#tutorial-title').onclick=quitToTitle;
function beginComSetup(choice){battleMode=choice.dataset.battle;selectOne('.mode-choice',choice);randomizeComPlayers();openSetup('com')}
$$('.mode-choice').forEach(b=>b.onclick=()=>beginComSetup(b));
// Capturing listener guarantees mode selection also works when the card's inner icon/text is clicked.
document.addEventListener('click',event=>{const choice=event.target.closest('.mode-choice');if(choice&&$('#mode-select').classList.contains('active'))beginComSetup(choice)},true);
$('#mode-next').onclick=()=>{randomizeComPlayers();openSetup('com')};
$$('.location-card').forEach(b=>b.onclick=()=>{settings.store=b.dataset.store;selectOne('.location-card',b);renderRoster()});$$('.swatch').forEach(b=>b.onclick=()=>{settings.avatar=b.dataset.color;selectOne('.swatch',b);applyAvatar($('#creator-preview'));renderRoster()});$$('.sex-choice button').forEach(b=>b.onclick=()=>{settings.sex=b.dataset.sex;selectOne('.sex-choice button',b);applyAvatar($('#creator-preview'))});$$('.currency').forEach(b=>b.onclick=()=>{settings.currency=b.dataset.currency;selectOne('.currency',b)});$$('.next').forEach(b=>b.onclick=()=>{if(step===1&&!validateName())return;step===2?toReady():showStep(step+1)});$('#player-name').addEventListener('input',validateName);setTimer();
document.addEventListener('keydown',e=>{if(e.target.matches('input, textarea'))return;if(['KeyW','KeyA','KeyS','KeyD','KeyT','KeyE','Space','ArrowLeft','ArrowRight','Escape'].includes(e.code))e.preventDefault();if(e.code==='Space'){if($('#title').classList.contains('active'))startTutorial();else if($('#mode-select').classList.contains('active')){randomizeComPlayers();openSetup('com')}else if($('#setup').classList.contains('active')){if(step===1&&!validateName())return;step===2?toReady():showStep(step+1)}else if($('#ready').classList.contains('active'))launch()}if(e.code==='Escape'){if($('#game').classList.contains('active')){if($('#quit-confirm').hidden)paused?resumeGame():pauseGame();else $('#quit-confirm').hidden=true}else if($('#ready').classList.contains('active')){changeScreen('setup');showStep(2)}else if($('#setup').classList.contains('active'))step===0?(playMode==='com'?openModeSelect():changeScreen('title')):showStep(step-1);else if($('#mode-select').classList.contains('active'))changeScreen('title')}if(e.code==='KeyW'||e.code==='ArrowUp')move(0,-4);if(e.code==='KeyS'||e.code==='ArrowDown')move(0,4);if(e.code==='KeyA'||e.code==='ArrowLeft')move(-4,0);if(e.code==='KeyD'||e.code==='ArrowRight')move(4,0);if(e.code==='KeyT')tryTake();if(e.code==='KeyE')checkout()});
