const stores={
 food:{name:"RAPIDO'S FOODLAND",sign:'FRESH • FAST • FUN',shelves:['PANTRY','FRESH PICKS'],items:[['Golden Apples',4.5,'🍎','#ed6554',31,58],['Mega Cereal',7.25,'🌟','#6e87d5',42,46],['Fresh Milk',5,'🥛','#e8f4f5',56,65],['Snack Stack',3.8,'🥨','#ee914c',68,45],['Power Juice',8.9,'🍊','#f2a23e',78,61],['Super Bites',6.6,'🍪','#c96f50',16,55],['Bread Loaf',3.25,'🍞','#d49a55',25,37],['Berry Box',6.45,'🫐','#5d6ec2',37,33],['Cheese Wheel',7.9,'🧀','#f7c34f',51,36],['Pasta Pack',4.2,'🍝','#e7b84b',63,33],['Iced Tea',3.6,'🧃','#f09349',73,39],['Cake Slice',9.5,'🍰','#f2819a',85,45]]},
 tech:{name:'TECHNO EXPRESS',sign:'POWER • PLAY • CONNECT',shelves:['GADGETS','GAMING'],items:[['Smart Watch',149,'⌚','#59b5e6',31,58],['Gaming Pad',65,'🎮','#9b69d3',42,46],['Headphones',89,'🎧','#ef674e',56,65],['Phone Pro',399,'📱','#4d789d',68,45],['Camera',249,'📷','#e2a543',78,61],['Laptop Air',599,'💻','#82bc9f',16,55],['VR Headset',319,'🥽','#4d5f79',25,37],['Smart Speaker',99,'🔊','#6c8dd2',37,33],['Keyboard',119,'⌨️','#7d7d90',51,36],['Drone Mini',179,'🚁','#e8a54c',63,33],['Power Bank',49,'🔋','#62ae7a',73,39],['Game Console',449,'🕹️','#e06c93',85,45]]}
};
// Extra stock opens up deeper store aisles as the player moves through the space.
stores.food.items.push(
 ['Spring Water',2.25,'💧','#54b8dd',12,66],['Sparkling Water',3.1,'🫧','#7fcde1',23,70],
 ['Iced Tea',3.6,'🧋','#c77c3d',35,69],['Empanadas',8.5,'🥟','#db9c49',47,70],
 ['Family Pizza',14.9,'🍕','#db7040',59,70],['Tomato Pasta',6.75,'🍝','#dca84e',71,70],
 ['Orange Soda',2.9,'🥤','#ee813c',84,68],['Salad Bowl',7.2,'🥗','#70ae68',11,44],
 ['Yogurt Pack',5.5,'🍦','#a06ab8',84,34],['Coffee Beans',11.4,'☕','#915b3e',48,29]
);
stores.tech.items.push(
 ['Ultra TV',899,'📺','#53627c',12,66],['Soundbar Pro',179,'🔊','#44505d',23,70],
 ['Smart Fridge',1099,'🧊','#a9bfcc',35,69],['Air Fryer',129,'🍳','#394653',47,70],
 ['Robot Vacuum',279,'🤖','#71849a',59,70],['Blender Max',99,'🥤','#e0604b',71,70],
 ['Coffee Machine',189,'☕','#44515e',84,68],['Microwave',159,'📦','#74838f',11,44],
 ['Washing Machine',649,'🧺','#607b95',84,34],['Projector',329,'📽️','#d0b253',48,29]
);
const currencyInfo={usd:{symbol:'$',name:'DOLLARS',code:'USD',rate:1},eur:{symbol:'€',name:'EUROS',code:'EUR',rate:.92},jpy:{symbol:'¥',name:'YENS',code:'JPY',rate:148}};
let settings={store:'food',avatar:'coral',currency:'usd',name:'YOU'},groceries=[],cart=[],playerX=48,playerY=73,active=false,step=0,timerId=null,botTimer=null,seconds=1200,playMode='solo',battleMode='ffa',comPlayers=[];
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="multiplayer.css" />');
const titleActions=document.createElement('div');titleActions.className='title-actions';
const soloButton=$('#start');soloButton.textContent='PLAY SOLO';soloButton.innerHTML='PLAY SOLO <strong>SPACE</strong>';
const comButton=document.createElement('button');comButton.className='com-button';comButton.textContent='PLAY WITH COM';
const multiButton=document.createElement('button');multiButton.className='multi-button';multiButton.textContent='MULTIPLAYER';
soloButton.replaceWith(titleActions);titleActions.append(soloButton,comButton,multiButton);
const modeScreen=document.createElement('section');modeScreen.id='mode-select';modeScreen.className='screen setup-screen';modeScreen.innerHTML='<div class="setup-head"><img class="brand-logo header-logo" src="supermarket-rapido-logo.png" alt="Supermarket Rapido"><span>COM MATCH</span></div><div class="setup-panel active mode-panel"><p class="kicker">PLAY WITH COM</p><h1>SELECT MODE</h1><div class="mode-grid"><button class="mode-choice selected" data-battle="ffa"><span>⚔️</span><strong>FREE-FOR-ALL</strong><small>Every shopper for themselves.</small></button><button class="mode-choice" data-battle="team"><span>🤝</span><strong>TEAM</strong><small>Work with a COM teammate.</small></button></div><button id="mode-next" class="next">NEXT →</button></div><div class="key-help"><kbd>ESC</kbd> BACK <span><kbd>SPACE</kbd> SELECT</span></div></section>';
document.querySelector('main').append(modeScreen);
const multiModal=document.createElement('div');multiModal.className='modal-shade';multiModal.hidden=true;multiModal.innerHTML='<div class="soon-card"><span class="big-icon">🌐</span><h2>MULTIPLAYER<br>COMING SOON!</h2><p>We\'re working in!<br>Come back later!</p><button>GOT IT</button></div>';document.querySelector('main').append(multiModal);
const roster=document.createElement('div');roster.id='com-roster';roster.className='com-roster';$('.character-select').after(roster);
const comArea=document.createElement('div');comArea.id='com-players';$('#items').after(comArea);
function randomizeComPlayers(){const names=['BYTE BOT','NOVA COM','PIXEL AI','GEAR UNIT'];const outfits=['coral','blue','violet','coral'];const spots=[[22,62],[39,48],[67,57],[81,42]];comPlayers=names.map((name,i)=>({name,outfit:outfits[(i+Math.floor(Math.random()*3))%outfits.length],score:0,x:spots[i][0],y:spots[i][1],target:null,taken:0}));renderRoster()}
function renderRoster(){if(playMode!=='com'){roster.hidden=true;return}roster.hidden=false;const human=settings.name||'YOU';roster.innerHTML=`<span class="roster-player human"><i class="dot" style="--outfit:${settings.avatar==='blue'?'#559de4':settings.avatar==='violet'?'#9c6bdb':'#ff7c57'}"></i>${human}</span>`+comPlayers.map(p=>`<span class="roster-player"><i class="bot">🤖</i><i class="dot" style="--outfit:${p.outfit==='blue'?'#559de4':p.outfit==='violet'?'#9c6bdb':'#ff7c57'}"></i>${p.name}</span>`).join('')}
function renderComPlayers(){if(playMode!=='com'){comArea.innerHTML='';return}comArea.innerHTML=comPlayers.map(p=>`<div class="com-shopper ${p.outfit}" style="left:${p.x}%;top:${p.y}%"><div class="character3d shopper3d"><div class="hair3d"></div><div class="head3d"><i></i><i></i><b></b></div><div class="torso3d"></div><div class="arm3d left-arm"></div><div class="arm3d right-arm"></div><div class="leg3d left-leg"></div><div class="leg3d right-leg"></div><em>🛒${p.taken||''}</em></div><span class="com-name">🤖 ${p.name}</span></div>`).join('')}
function startBots(){clearInterval(botTimer);if(playMode!=='com')return;botTimer=setInterval(()=>{if(!active)return;comPlayers.forEach((bot,index)=>{let target=groceries[bot.target];if(!target||target.picked){const available=groceries.map((g,i)=>({g,i})).filter(x=>!x.g.picked);if(!available.length)return;const choice=available[Math.floor(Math.random()*available.length)];bot.target=choice.i;target=choice.g}bot.x+=Math.sign(target.x-bot.x)*Math.min(4,Math.abs(target.x-bot.x));bot.y+=Math.sign(target.y-bot.y)*Math.min(3,Math.abs(target.y-bot.y));if(Math.hypot(target.x-bot.x,target.y-bot.y)<6){target.picked=true;bot.score+=target.price;bot.taken++;bot.target=null;draw()}const botNode=comArea.children[index];if(botNode){botNode.style.left=bot.x+'%';botNode.style.top=bot.y+'%';botNode.querySelector('em').textContent='🛒'+(bot.taken||'')}})},850)}
const nameError=document.createElement('small');
nameError.id='name-error';nameError.className='name-error';nameError.textContent='Player Name is required.';nameError.hidden=true;nameError.style.cssText='color:#ffe371;font-size:11px;font-weight:900;margin-top:2px';
$('#player-name').after(nameError);
$('#player-name').value='';
function validateName(){const value=$('#player-name').value.trim(),input=$('#player-name'),invalid=!value;nameError.hidden=!invalid;input.style.borderColor=invalid?'#ff7659':'#a8e3bc';input.style.boxShadow=invalid?'0 0 0 3px #fb614244':'none';if(!invalid){settings.name=value.toUpperCase();renderRoster()}return !invalid}
function format(n){const c=currencyInfo[settings.currency],amount=n*c.rate;return c.symbol+(settings.currency==='jpy'?Math.round(amount):amount.toFixed(2))}
function changeScreen(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function selectOne(selector,current){$$(selector).forEach(b=>b.classList.toggle('selected',b===current))}
function showStep(n){step=Math.max(0,Math.min(2,n));$$('#setup .setup-panel').forEach((p,i)=>p.classList.toggle('active',i===step));$('#step-count').textContent=`${step+1} / 3`}
function applyAvatar(node){node.classList.remove('blue','violet');if(settings.avatar!=='coral')node.classList.add(settings.avatar)}
function updateReady(){const c=currencyInfo[settings.currency];$('#ready-name').textContent=settings.name||'YOU';$('#ready-location').textContent=stores[settings.store].name;$('#ready-currency').textContent=`${c.name} (${c.code})`;applyAvatar($('#ready-avatar'))}
function openSetup(mode='solo'){playMode=mode;changeScreen('setup');showStep(0);renderRoster()}
function openModeSelect(){playMode='com';changeScreen('mode-select');modeScreen.classList.add('active')}
function toReady(){updateReady();renderRoster();changeScreen('ready')}
function makeItems(){groceries=stores[settings.store].items.map(([name,price,icon,color,x,y])=>({name,price,icon,color,x,y,picked:false}))}
function draw(){const area=$('#items');area.innerHTML='';groceries.forEach((g,i)=>{if(g.picked)return;const e=document.createElement('button');e.className='item';e.dataset.index=i;const scale=.64+g.y/130;e.style.cssText=`left:${g.x}%;top:${g.y}%;--color:${g.color};--item-scale:${scale};z-index:${Math.round(g.y*10)}`;e.innerHTML=`<b class="price">${format(g.price)}</b><span class="box" data-icon="${g.icon}"></span><small>${g.name}</small>`;e.onclick=()=>tryTake(i);area.append(e)});updateTakePrompt()}
function update(){const sum=cart.reduce((a,g)=>a+g.price,0);$('#total').textContent=format(sum);$('#regtotal').textContent=format(sum);$('#cart').innerHTML=cart.length?cart.map(g=>`<span class="chip">${g.icon} ${g.name}</span>`).join(''):'Your basket is empty!';$('#player em').textContent=cart.length?`🛒${cart.length}`:'🛒'}
function nearestItem(){let match=null,best=Infinity;groceries.forEach((g,i)=>{if(g.picked)return;const d=Math.hypot((g.x-playerX)*.78,(g.y-playerY));if(d<best){best=d;match={g,i,d}}});return match}
function updateTakePrompt(){const near=nearestItem(),hint=$('.instructions');$$('.item').forEach(e=>e.classList.remove('near'));if(near&&near.d<8){const el=$(`.item[data-index="${near.i}"]`);if(el)el.classList.add('near');hint.textContent=`PRESS T TO TAKE ${near.g.name.toUpperCase()} • E TO CHECK OUT`}else hint.textContent='W/S: forward & back • A/D: move sideways • T: take item • E: check out'}
function tryTake(index){const near=nearestItem();if(index!==undefined&&(!near||near.i!==index))return;if(!near||near.d>=8||!active)return;const g=near.g;g.picked=true;cart.push(g);update();draw()}
function updatePlayer(walking=false){const player=$('#player'),scale=.58+playerY/110;player.style.left=playerX+'%';player.style.top=playerY+'%';player.style.bottom='auto';player.style.zIndex=Math.round(playerY*10);player.style.transform=`scale(${scale})`;player.classList.toggle('walking',walking);updateTakePrompt()}
function reset(){cart=[];playerX=48;playerY=73;makeItems();$('#player label').textContent=settings.name||'YOU';applyAvatar($('#player'));update();draw();updatePlayer()}
function setTimer(){const m=Math.floor(seconds/60),s=seconds%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('warning',seconds<=60)}
function startTimer(){clearInterval(timerId);seconds=1200;setTimer();timerId=setInterval(()=>{seconds--;setTimer();if(seconds<=0){clearInterval(timerId);checkout(true)}},1000)}
function launch(){changeScreen('game');active=true;$('#game-location').textContent=stores[settings.store].name;$('#back-sign').textContent=stores[settings.store].sign;$('#shelf-left').textContent=stores[settings.store].shelves[0];$('#shelf-right').textContent=stores[settings.store].shelves[1];reset();renderComPlayers();startBots();startTimer()}
function move(dx,dy){if(!active)return;playerX=Math.max(7,Math.min(88,playerX+dx));playerY=Math.max(28,Math.min(76,playerY+dy));updatePlayer(true);clearTimeout(move.stop);move.stop=setTimeout(()=>$('#player').classList.remove('walking'),125)}
function checkout(outOfTime=false){if(!active)return;if(!cart.length&&!outOfTime)return;active=false;clearInterval(timerId);clearInterval(botTimer);const sum=cart.reduce((a,g)=>a+g.price,0);changeScreen('results');$('#final').textContent=format(sum);$('#your-score').textContent=format(sum);$('#winner').textContent=outOfTime?'TIME UP!':sum>=18.75?'SUPER SHOPPER!':'GOOD SHOPPING!';$('#results-kicker').textContent=outOfTime?'THE CLOCK RAN OUT':stores[settings.store].name+' WINNER';if(playMode==='com'){const rows=[{name:settings.name||'YOU',score:sum,human:true},...comPlayers].sort((a,b)=>b.score-a.score);$('.board').innerHTML=rows.map(p=>`${p.human?'':'<span class="bot">🤖</span>'}${p.name} <b>${format(p.score)}</b>`).join('<br>')}else $('.board').innerHTML=`YOU <b>${format(sum)}</b><br>CASA CART <b>${format(18.75)}</b><br>QUICK MARTY <b>${format(13.2)}</b>`}
$('#start').onclick=()=>openSetup('solo');comButton.onclick=()=>openModeSelect();comButton.addEventListener('pointerup',event=>{event.preventDefault();openModeSelect()});multiButton.onclick=()=>multiModal.hidden=false;multiModal.querySelector('button').onclick=()=>multiModal.hidden=true;$('#launch').onclick=launch;$('#again').onclick=()=>openSetup(playMode);
function beginComSetup(choice){battleMode=choice.dataset.battle;selectOne('.mode-choice',choice);randomizeComPlayers();openSetup('com')}
$$('.mode-choice').forEach(b=>b.onclick=()=>beginComSetup(b));
// Capturing listener guarantees mode selection also works when the card's inner icon/text is clicked.
document.addEventListener('click',event=>{const choice=event.target.closest('.mode-choice');if(choice&&$('#mode-select').classList.contains('active'))beginComSetup(choice)},true);
$('#mode-next').onclick=()=>{randomizeComPlayers();openSetup('com')};
$$('.location-card').forEach(b=>b.onclick=()=>{settings.store=b.dataset.store;selectOne('.location-card',b)});$$('.avatar-option').forEach(b=>b.onclick=()=>{settings.avatar=b.dataset.avatar;selectOne('.avatar-option',b);$$('.swatch').forEach(s=>s.classList.toggle('selected',s.dataset.color===settings.avatar))});$$('.swatch').forEach(b=>b.onclick=()=>{settings.avatar=b.dataset.color;selectOne('.swatch',b);$$('.avatar-option').forEach(a=>a.classList.toggle('selected',a.dataset.avatar===settings.avatar))});$$('.currency').forEach(b=>b.onclick=()=>{settings.currency=b.dataset.currency;selectOne('.currency',b)});$$('.next').forEach(b=>b.onclick=()=>{if(step===1&&!validateName())return;step===2?toReady():showStep(step+1)});$('#player-name').addEventListener('input',validateName);
document.addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyT','KeyE','Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Space'){if($('#title').classList.contains('active'))openSetup('solo');else if($('#mode-select').classList.contains('active')){randomizeComPlayers();openSetup('com')}else if($('#setup').classList.contains('active')){if(step===1&&!validateName())return;step===2?toReady():showStep(step+1)}else if($('#ready').classList.contains('active'))launch()}if(e.code==='Escape'){if($('#ready').classList.contains('active')){changeScreen('setup');showStep(2)}else if($('#setup').classList.contains('active'))step===0?(playMode==='com'?openModeSelect():changeScreen('title')):showStep(step-1);else if($('#mode-select').classList.contains('active'))changeScreen('title')}if(e.code==='KeyW'||e.code==='ArrowUp')move(0,-4);if(e.code==='KeyS'||e.code==='ArrowDown')move(0,4);if(e.code==='KeyA'||e.code==='ArrowLeft')move(-4,0);if(e.code==='KeyD'||e.code==='ArrowRight')move(4,0);if(e.code==='KeyT')tryTake();if(e.code==='KeyE')checkout()});
